language: node_js
before_script:
 - npm run build
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
sudo: false
services:
  - mongodb
script:
  - npm test
  - npm run doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
